spring:
  profiles:
    active: dev # 激活开发环境配置

---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml        # mybatis的核心配置文件所在路径
  type-aliases-package: com.seven.springcloud.entity        # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
  profiles: dev # 开发环境
  application:
    name: microservice-product-config-bus                   # ******服务名*******
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8  # 数据库连接地址，*****注意库名 db01***************
    username: learning
    password: learning
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

eureka:
  client:
    registerWithEureka: true  # 服务注册开关
    fetchRegistry: true       # 服务发现开关
    serviceUrl:               # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port} # 等价于 microservice-product:8001
    prefer-ip-address: true                                # 访问路径就会显示成IP地址

emp:
  name:
    wangwu
    
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml        # mybatis的核心配置文件所在路径
  type-aliases-package: com.seven.springcloud.entity        # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
  profiles: prod # 生产环境
  application:
    name: microservice-product-config                       # ******服务名*******
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8  # 数据库连接地址，*****注意库名 db02***************
    username: learning
    password: learning
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

eureka:
  client:
    registerWithEureka: true  # 服务注册开关
    fetchRegistry: true       # 服务发现开关
    serviceUrl:               # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port} # 等价于 microservice-product:8001
    prefer-ip-address: true                                # 访问路径就会显示成IP地址


